"""empty message

Revision ID: 292d12ec8e44
Revises: 4895af7f9964
Create Date: 2021-01-12 22:30:55.157935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292d12ec8e44'
down_revision = '4895af7f9964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('time_a', sa.Integer(), nullable=True),
    sa.Column('time_b', sa.Integer(), nullable=True),
    sa.Column('time_c', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puzzle')
    # ### end Alembic commands ###
