"""empty message

Revision ID: 82c03acf897b
Revises: c390f267bad2
Create Date: 2020-12-30 23:53:48.370516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c03acf897b'
down_revision = 'c390f267bad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stu_info', sa.Column('belong', sa.String(length=256), nullable=True))
    op.add_column('stu_info', sa.Column('college', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stu_info', 'college')
    op.drop_column('stu_info', 'belong')
    # ### end Alembic commands ###
