/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMdiArea>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionNew;
    QAction *actionOpen;
    QAction *actionSave;
    QAction *actionSaveAs;
    QAction *actionExit;
    QAction *actionUndo;
    QAction *actionRedo;
    QAction *actionCut;
    QAction *actionCopy;
    QAction *actionPaste;
    QAction *actionClose;
    QAction *actionCloseAll;
    QAction *actionTile;
    QAction *actionCascade;
    QAction *actionNext;
    QAction *actionPrevious;
    QAction *actionAboutQt;
    QAction *actionLL;
    QAction *action_L;
    QAction *actionSA;
    QAction *actionLetIn;
    QAction *actionBig_Data;
    QAction *actionbold;
    QAction *actionitalic;
    QAction *actionRedd;
    QAction *actionYeloww;
    QAction *actionGreenn;
    QAction *actionBluee;
    QAction *actionBlueee;
    QAction *actionGreen;
    QAction *actionYellowww;
    QAction *actionmagenta;
    QAction *actionlightGray;
    QAction *action_2;
    QAction *action_3;
    QAction *actionblue;
    QAction *actiongreen;
    QAction *actionred;
    QAction *actiongrey;
    QAction *action_4;
    QAction *action28;
    QAction *action_5;
    QAction *action_6;
    QAction *action_7;
    QAction *action_8;
    QAction *action_9;
    QAction *action_10;
    QAction *action_11;
    QAction *action_12;
    QAction *action1;
    QAction *action10;
    QAction *action20;
    QAction *action30;
    QAction *action40;
    QAction *action25;
    QAction *action26;
    QAction *action27;
    QAction *action28_2;
    QAction *action29;
    QAction *action30_2;
    QAction *action31;
    QAction *action32;
    QAction *action33;
    QAction *action34;
    QAction *action35;
    QAction *action36;
    QAction *actionshx;
    QAction *actionHome_https_lvyingzhao_cn;
    QAction *actionchangkou;
    QWidget *centralWidget;
    QGridLayout *gridLayout;
    QMdiArea *mdiArea;
    QMenuBar *menuBar;
    QMenu *menuF;
    QMenu *menuE;
    QMenu *menuW;
    QMenu *menuH;
    QMenu *menu_A;
    QMenu *menu;
    QMenu *menu_2;
    QMenu *menu_3;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(712, 500);
        actionNew = new QAction(MainWindow);
        actionNew->setObjectName(QStringLiteral("actionNew"));
        QIcon icon;
        icon.addFile(QStringLiteral(":/icon/image/NewDocumentHS.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionNew->setIcon(icon);
        QFont font;
        font.setFamily(QStringLiteral("Arial"));
        font.setPointSize(12);
        font.setItalic(false);
        actionNew->setFont(font);
        actionOpen = new QAction(MainWindow);
        actionOpen->setObjectName(QStringLiteral("actionOpen"));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/icon/image/openHS.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpen->setIcon(icon1);
        QFont font1;
        font1.setPointSize(12);
        actionOpen->setFont(font1);
        actionSave = new QAction(MainWindow);
        actionSave->setObjectName(QStringLiteral("actionSave"));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/icon/image/saveHS.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave->setIcon(icon2);
        actionSave->setFont(font1);
        actionSaveAs = new QAction(MainWindow);
        actionSaveAs->setObjectName(QStringLiteral("actionSaveAs"));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/icon/image/SaveAllHS.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSaveAs->setIcon(icon3);
        actionSaveAs->setFont(font1);
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QStringLiteral("actionExit"));
        actionUndo = new QAction(MainWindow);
        actionUndo->setObjectName(QStringLiteral("actionUndo"));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/icon/image/Edit_UndoHS.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionUndo->setIcon(icon4);
        actionUndo->setFont(font1);
        actionRedo = new QAction(MainWindow);
        actionRedo->setObjectName(QStringLiteral("actionRedo"));
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/icon/image/Edit_RedoHS.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRedo->setIcon(icon5);
        actionRedo->setFont(font1);
        actionCut = new QAction(MainWindow);
        actionCut->setObjectName(QStringLiteral("actionCut"));
        QIcon icon6;
        icon6.addFile(QStringLiteral(":/icon/image/CutHS.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCut->setIcon(icon6);
        actionCut->setFont(font1);
        actionCopy = new QAction(MainWindow);
        actionCopy->setObjectName(QStringLiteral("actionCopy"));
        QIcon icon7;
        icon7.addFile(QStringLiteral(":/icon/image/CopyHS.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCopy->setIcon(icon7);
        actionCopy->setFont(font1);
        actionPaste = new QAction(MainWindow);
        actionPaste->setObjectName(QStringLiteral("actionPaste"));
        QIcon icon8;
        icon8.addFile(QStringLiteral(":/icon/image/PasteHS.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionPaste->setIcon(icon8);
        actionPaste->setFont(font1);
        actionClose = new QAction(MainWindow);
        actionClose->setObjectName(QStringLiteral("actionClose"));
        actionClose->setFont(font1);
        actionCloseAll = new QAction(MainWindow);
        actionCloseAll->setObjectName(QStringLiteral("actionCloseAll"));
        actionCloseAll->setFont(font1);
        actionTile = new QAction(MainWindow);
        actionTile->setObjectName(QStringLiteral("actionTile"));
        actionTile->setFont(font1);
        actionCascade = new QAction(MainWindow);
        actionCascade->setObjectName(QStringLiteral("actionCascade"));
        actionCascade->setFont(font1);
        actionNext = new QAction(MainWindow);
        actionNext->setObjectName(QStringLiteral("actionNext"));
        actionNext->setFont(font1);
        actionPrevious = new QAction(MainWindow);
        actionPrevious->setObjectName(QStringLiteral("actionPrevious"));
        actionPrevious->setFont(font1);
        actionAboutQt = new QAction(MainWindow);
        actionAboutQt->setObjectName(QStringLiteral("actionAboutQt"));
        actionAboutQt->setFont(font1);
        actionLL = new QAction(MainWindow);
        actionLL->setObjectName(QStringLiteral("actionLL"));
        QIcon icon9;
        icon9.addFile(QStringLiteral("image/lluu.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLL->setIcon(icon9);
        actionLL->setFont(font1);
        action_L = new QAction(MainWindow);
        action_L->setObjectName(QStringLiteral("action_L"));
        QIcon icon10;
        icon10.addFile(QStringLiteral("image/clear.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_L->setIcon(icon10);
        action_L->setFont(font1);
        actionSA = new QAction(MainWindow);
        actionSA->setObjectName(QStringLiteral("actionSA"));
        QIcon icon11;
        icon11.addFile(QStringLiteral("image/selectAll.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSA->setIcon(icon11);
        actionSA->setFont(font1);
        actionLetIn = new QAction(MainWindow);
        actionLetIn->setObjectName(QStringLiteral("actionLetIn"));
        QIcon icon12;
        icon12.addFile(QStringLiteral("image/letIn.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLetIn->setIcon(icon12);
        actionLetIn->setFont(font1);
        actionBig_Data = new QAction(MainWindow);
        actionBig_Data->setObjectName(QStringLiteral("actionBig_Data"));
        actionbold = new QAction(MainWindow);
        actionbold->setObjectName(QStringLiteral("actionbold"));
        QIcon icon13;
        icon13.addFile(QStringLiteral("image/bold.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionbold->setIcon(icon13);
        actionbold->setFont(font1);
        actionitalic = new QAction(MainWindow);
        actionitalic->setObjectName(QStringLiteral("actionitalic"));
        QIcon icon14;
        icon14.addFile(QStringLiteral("image/italic.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionitalic->setIcon(icon14);
        actionitalic->setFont(font1);
        actionRedd = new QAction(MainWindow);
        actionRedd->setObjectName(QStringLiteral("actionRedd"));
        actionRedd->setFont(font1);
        actionYeloww = new QAction(MainWindow);
        actionYeloww->setObjectName(QStringLiteral("actionYeloww"));
        actionYeloww->setFont(font1);
        actionGreenn = new QAction(MainWindow);
        actionGreenn->setObjectName(QStringLiteral("actionGreenn"));
        actionGreenn->setFont(font1);
        actionBluee = new QAction(MainWindow);
        actionBluee->setObjectName(QStringLiteral("actionBluee"));
        actionBluee->setFont(font1);
        actionBlueee = new QAction(MainWindow);
        actionBlueee->setObjectName(QStringLiteral("actionBlueee"));
        actionBlueee->setFont(font1);
        actionGreen = new QAction(MainWindow);
        actionGreen->setObjectName(QStringLiteral("actionGreen"));
        actionGreen->setFont(font1);
        actionYellowww = new QAction(MainWindow);
        actionYellowww->setObjectName(QStringLiteral("actionYellowww"));
        actionYellowww->setFont(font1);
        actionmagenta = new QAction(MainWindow);
        actionmagenta->setObjectName(QStringLiteral("actionmagenta"));
        actionmagenta->setFont(font1);
        actionlightGray = new QAction(MainWindow);
        actionlightGray->setObjectName(QStringLiteral("actionlightGray"));
        actionlightGray->setFont(font1);
        action_2 = new QAction(MainWindow);
        action_2->setObjectName(QStringLiteral("action_2"));
        action_3 = new QAction(MainWindow);
        action_3->setObjectName(QStringLiteral("action_3"));
        actionblue = new QAction(MainWindow);
        actionblue->setObjectName(QStringLiteral("actionblue"));
        QIcon icon15;
        icon15.addFile(QStringLiteral("image/blue.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionblue->setIcon(icon15);
        actionblue->setFont(font1);
        actiongreen = new QAction(MainWindow);
        actiongreen->setObjectName(QStringLiteral("actiongreen"));
        QIcon icon16;
        icon16.addFile(QStringLiteral("image/green.png"), QSize(), QIcon::Normal, QIcon::Off);
        actiongreen->setIcon(icon16);
        actiongreen->setFont(font1);
        actionred = new QAction(MainWindow);
        actionred->setObjectName(QStringLiteral("actionred"));
        QIcon icon17;
        icon17.addFile(QStringLiteral("image/red.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionred->setIcon(icon17);
        actionred->setFont(font1);
        actiongrey = new QAction(MainWindow);
        actiongrey->setObjectName(QStringLiteral("actiongrey"));
        QIcon icon18;
        icon18.addFile(QStringLiteral("image/grey.png"), QSize(), QIcon::Normal, QIcon::Off);
        actiongrey->setIcon(icon18);
        actiongrey->setFont(font1);
        action_4 = new QAction(MainWindow);
        action_4->setObjectName(QStringLiteral("action_4"));
        action_4->setFont(font1);
        action28 = new QAction(MainWindow);
        action28->setObjectName(QStringLiteral("action28"));
        action_5 = new QAction(MainWindow);
        action_5->setObjectName(QStringLiteral("action_5"));
        action_5->setFont(font1);
        action_6 = new QAction(MainWindow);
        action_6->setObjectName(QStringLiteral("action_6"));
        action_6->setFont(font1);
        action_7 = new QAction(MainWindow);
        action_7->setObjectName(QStringLiteral("action_7"));
        action_7->setFont(font1);
        action_8 = new QAction(MainWindow);
        action_8->setObjectName(QStringLiteral("action_8"));
        action_8->setFont(font1);
        action_9 = new QAction(MainWindow);
        action_9->setObjectName(QStringLiteral("action_9"));
        action_9->setFont(font1);
        action_10 = new QAction(MainWindow);
        action_10->setObjectName(QStringLiteral("action_10"));
        action_10->setFont(font1);
        action_11 = new QAction(MainWindow);
        action_11->setObjectName(QStringLiteral("action_11"));
        action_11->setFont(font1);
        action_12 = new QAction(MainWindow);
        action_12->setObjectName(QStringLiteral("action_12"));
        action_12->setFont(font1);
        action1 = new QAction(MainWindow);
        action1->setObjectName(QStringLiteral("action1"));
        action1->setFont(font1);
        action10 = new QAction(MainWindow);
        action10->setObjectName(QStringLiteral("action10"));
        action10->setFont(font1);
        action20 = new QAction(MainWindow);
        action20->setObjectName(QStringLiteral("action20"));
        action20->setFont(font1);
        action30 = new QAction(MainWindow);
        action30->setObjectName(QStringLiteral("action30"));
        action30->setFont(font1);
        action40 = new QAction(MainWindow);
        action40->setObjectName(QStringLiteral("action40"));
        action40->setFont(font1);
        action25 = new QAction(MainWindow);
        action25->setObjectName(QStringLiteral("action25"));
        action25->setFont(font1);
        action26 = new QAction(MainWindow);
        action26->setObjectName(QStringLiteral("action26"));
        action26->setFont(font1);
        action27 = new QAction(MainWindow);
        action27->setObjectName(QStringLiteral("action27"));
        action27->setFont(font1);
        action28_2 = new QAction(MainWindow);
        action28_2->setObjectName(QStringLiteral("action28_2"));
        action28_2->setFont(font1);
        action29 = new QAction(MainWindow);
        action29->setObjectName(QStringLiteral("action29"));
        action29->setFont(font1);
        action30_2 = new QAction(MainWindow);
        action30_2->setObjectName(QStringLiteral("action30_2"));
        action30_2->setFont(font1);
        action31 = new QAction(MainWindow);
        action31->setObjectName(QStringLiteral("action31"));
        action31->setFont(font1);
        action32 = new QAction(MainWindow);
        action32->setObjectName(QStringLiteral("action32"));
        action32->setFont(font1);
        action33 = new QAction(MainWindow);
        action33->setObjectName(QStringLiteral("action33"));
        action33->setFont(font1);
        action34 = new QAction(MainWindow);
        action34->setObjectName(QStringLiteral("action34"));
        action34->setFont(font1);
        action35 = new QAction(MainWindow);
        action35->setObjectName(QStringLiteral("action35"));
        action35->setFont(font1);
        action36 = new QAction(MainWindow);
        action36->setObjectName(QStringLiteral("action36"));
        action36->setFont(font1);
        actionshx = new QAction(MainWindow);
        actionshx->setObjectName(QStringLiteral("actionshx"));
        QIcon icon19;
        icon19.addFile(QStringLiteral("image/delete.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionshx->setIcon(icon19);
        actionshx->setFont(font1);
        actionHome_https_lvyingzhao_cn = new QAction(MainWindow);
        actionHome_https_lvyingzhao_cn->setObjectName(QStringLiteral("actionHome_https_lvyingzhao_cn"));
        actionchangkou = new QAction(MainWindow);
        actionchangkou->setObjectName(QStringLiteral("actionchangkou"));
        actionchangkou->setFont(font1);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        gridLayout = new QGridLayout(centralWidget);
        gridLayout->setSpacing(6);
        gridLayout->setContentsMargins(11, 11, 11, 11);
        gridLayout->setObjectName(QStringLiteral("gridLayout"));
        mdiArea = new QMdiArea(centralWidget);
        mdiArea->setObjectName(QStringLiteral("mdiArea"));

        gridLayout->addWidget(mdiArea, 0, 0, 1, 1);

        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 712, 27));
        menuBar->setFont(font1);
        menuF = new QMenu(menuBar);
        menuF->setObjectName(QStringLiteral("menuF"));
        menuF->setFont(font1);
        menuE = new QMenu(menuBar);
        menuE->setObjectName(QStringLiteral("menuE"));
        menuE->setFont(font1);
        menuW = new QMenu(menuBar);
        menuW->setObjectName(QStringLiteral("menuW"));
        menuW->setFont(font1);
        menuH = new QMenu(menuBar);
        menuH->setObjectName(QStringLiteral("menuH"));
        menuH->setFont(font1);
        menu_A = new QMenu(menuH);
        menu_A->setObjectName(QStringLiteral("menu_A"));
        menu = new QMenu(menuBar);
        menu->setObjectName(QStringLiteral("menu"));
        menu_2 = new QMenu(menuBar);
        menu_2->setObjectName(QStringLiteral("menu_2"));
        menu_3 = new QMenu(menuBar);
        menu_3->setObjectName(QStringLiteral("menu_3"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        mainToolBar->setFont(font1);
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuF->menuAction());
        menuBar->addAction(menuE->menuAction());
        menuBar->addAction(menuW->menuAction());
        menuBar->addAction(menu->menuAction());
        menuBar->addAction(menu_2->menuAction());
        menuBar->addAction(menu_3->menuAction());
        menuBar->addAction(menuH->menuAction());
        menuF->addAction(actionNew);
        menuF->addAction(actionOpen);
        menuF->addSeparator();
        menuF->addAction(actionSave);
        menuF->addAction(actionSaveAs);
        menuF->addSeparator();
        menuF->addAction(actionExit);
        menuE->addAction(actionUndo);
        menuE->addAction(actionRedo);
        menuE->addAction(actionCut);
        menuE->addAction(actionCopy);
        menuE->addAction(actionPaste);
        menuE->addAction(action_4);
        menuE->addAction(action28);
        menuW->addAction(actionClose);
        menuW->addAction(actionCloseAll);
        menuW->addAction(actionTile);
        menuW->addAction(actionCascade);
        menuW->addSeparator();
        menuW->addAction(actionNext);
        menuW->addAction(actionPrevious);
        menuW->addAction(actionchangkou);
        menuH->addAction(menu_A->menuAction());
        menuH->addAction(actionAboutQt);
        menu_A->addAction(actionBig_Data);
        menu_A->addSeparator();
        menu_A->addAction(action_2);
        menu_A->addAction(action_3);
        menu_A->addAction(actionHome_https_lvyingzhao_cn);
        menu->addAction(actionRedd);
        menu->addAction(actionYeloww);
        menu->addAction(actionGreenn);
        menu->addAction(actionBluee);
        menu->addAction(actionBlueee);
        menu->addAction(actionGreen);
        menu->addAction(actionYellowww);
        menu->addAction(actionmagenta);
        menu->addAction(actionlightGray);
        menu_2->addAction(action_5);
        menu_2->addAction(action_6);
        menu_2->addAction(action_7);
        menu_2->addAction(action_8);
        menu_2->addAction(action_9);
        menu_2->addAction(action_10);
        menu_2->addAction(action_11);
        menu_2->addAction(action_12);
        menu_3->addAction(action1);
        menu_3->addAction(action10);
        menu_3->addAction(action20);
        menu_3->addAction(action30);
        menu_3->addAction(action40);
        menu_3->addAction(action25);
        menu_3->addAction(action26);
        menu_3->addAction(action27);
        menu_3->addAction(action28_2);
        menu_3->addAction(action29);
        menu_3->addAction(action30_2);
        menu_3->addAction(action31);
        menu_3->addAction(action32);
        menu_3->addAction(action33);
        menu_3->addAction(action34);
        menu_3->addAction(action35);
        menu_3->addAction(action36);
        mainToolBar->addAction(actionNew);
        mainToolBar->addAction(actionOpen);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionSave);
        mainToolBar->addAction(actionSaveAs);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionUndo);
        mainToolBar->addAction(actionRedo);
        mainToolBar->addAction(actionCut);
        mainToolBar->addAction(actionCopy);
        mainToolBar->addAction(actionPaste);
        mainToolBar->addAction(action_L);
        mainToolBar->addAction(actionLetIn);
        mainToolBar->addAction(actionSA);
        mainToolBar->addAction(actionLL);
        mainToolBar->addAction(actionshx);
        mainToolBar->addAction(actionbold);
        mainToolBar->addAction(actionitalic);
        mainToolBar->addAction(actiongreen);
        mainToolBar->addAction(actionred);
        mainToolBar->addAction(actiongrey);
        mainToolBar->addAction(actionblue);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        actionNew->setText(QApplication::translate("MainWindow", "\346\226\260\345\273\272\346\226\207\344\273\266(&N)", Q_NULLPTR));
        actionOpen->setText(QApplication::translate("MainWindow", "\346\211\223\345\274\200\346\226\207\344\273\266(&O)", Q_NULLPTR));
        actionSave->setText(QApplication::translate("MainWindow", "\344\277\235\345\255\230(&S)", Q_NULLPTR));
        actionSaveAs->setText(QApplication::translate("MainWindow", "\345\217\246\345\255\230\344\270\272(&A)", Q_NULLPTR));
        actionExit->setText(QApplication::translate("MainWindow", "\351\200\200\345\207\272(&X)", Q_NULLPTR));
        actionUndo->setText(QApplication::translate("MainWindow", "\346\222\244\351\224\200(&U)", Q_NULLPTR));
        actionRedo->setText(QApplication::translate("MainWindow", "\346\201\242\345\244\215(&R)", Q_NULLPTR));
        actionCut->setText(QApplication::translate("MainWindow", "\345\211\252\345\210\207(&T)", Q_NULLPTR));
        actionCopy->setText(QApplication::translate("MainWindow", "\345\244\215\345\210\266(&C)", Q_NULLPTR));
        actionPaste->setText(QApplication::translate("MainWindow", "\347\262\230\350\264\264(&P)", Q_NULLPTR));
        actionClose->setText(QApplication::translate("MainWindow", "\345\205\263\351\227\255(&O)", Q_NULLPTR));
        actionCloseAll->setText(QApplication::translate("MainWindow", "\345\205\263\351\227\255\346\211\200\346\234\211\347\252\227\345\217\243(&A)", Q_NULLPTR));
        actionTile->setText(QApplication::translate("MainWindow", "\345\271\263\351\223\272(&T)", Q_NULLPTR));
        actionCascade->setText(QApplication::translate("MainWindow", "\345\261\202\345\217\240(&C)", Q_NULLPTR));
        actionNext->setText(QApplication::translate("MainWindow", "\344\270\213\344\270\200\344\270\252(&X)", Q_NULLPTR));
        actionPrevious->setText(QApplication::translate("MainWindow", "\345\211\215\344\270\200\344\270\252(&V)", Q_NULLPTR));
        actionAboutQt->setText(QApplication::translate("MainWindow", "\345\205\263\344\272\216Qt(&Q)", Q_NULLPTR));
        actionLL->setText(QApplication::translate("MainWindow", "\344\270\213\345\210\222\347\272\277(I)", Q_NULLPTR));
        action_L->setText(QApplication::translate("MainWindow", "\346\270\205\347\251\272(L)", Q_NULLPTR));
        actionSA->setText(QApplication::translate("MainWindow", "\345\205\250\351\200\211", Q_NULLPTR));
        actionLetIn->setText(QApplication::translate("MainWindow", "\346\217\222\345\205\245", Q_NULLPTR));
        actionBig_Data->setText(QApplication::translate("MainWindow", "08193109\n"
"", Q_NULLPTR));
        actionbold->setText(QApplication::translate("MainWindow", "Bold", Q_NULLPTR));
        actionitalic->setText(QApplication::translate("MainWindow", "Italic", Q_NULLPTR));
        actionRedd->setText(QApplication::translate("MainWindow", "\347\272\242", Q_NULLPTR));
        actionYeloww->setText(QApplication::translate("MainWindow", "\351\273\204", Q_NULLPTR));
        actionGreenn->setText(QApplication::translate("MainWindow", "\347\273\277", Q_NULLPTR));
        actionBluee->setText(QApplication::translate("MainWindow", "\350\223\235", Q_NULLPTR));
        actionBlueee->setText(QApplication::translate("MainWindow", "\351\273\221\350\223\235", Q_NULLPTR));
        actionGreen->setText(QApplication::translate("MainWindow", "\351\273\221\347\273\277", Q_NULLPTR));
        actionYellowww->setText(QApplication::translate("MainWindow", "\351\273\221\351\273\204", Q_NULLPTR));
        actionmagenta->setText(QApplication::translate("MainWindow", "magenta", Q_NULLPTR));
        actionlightGray->setText(QApplication::translate("MainWindow", "lightGray", Q_NULLPTR));
        action_2->setText(QApplication::translate("MainWindow", "       \345\220\225\350\277\216\346\234\235\n"
"  ", Q_NULLPTR));
        action_3->setText(QApplication::translate("MainWindow", "github:boopo", Q_NULLPTR));
        actionblue->setText(QApplication::translate("MainWindow", "blue", Q_NULLPTR));
        actiongreen->setText(QApplication::translate("MainWindow", "green", Q_NULLPTR));
        actionred->setText(QApplication::translate("MainWindow", "red", Q_NULLPTR));
        actiongrey->setText(QApplication::translate("MainWindow", "grey", Q_NULLPTR));
        action_4->setText(QApplication::translate("MainWindow", "\345\256\213", Q_NULLPTR));
        action28->setText(QApplication::translate("MainWindow", "hgfhfhj", Q_NULLPTR));
        action_5->setText(QApplication::translate("MainWindow", "\345\256\213\344\275\223", Q_NULLPTR));
        action_6->setText(QApplication::translate("MainWindow", "\345\276\256\350\275\257\351\233\205\351\273\221", Q_NULLPTR));
        action_7->setText(QApplication::translate("MainWindow", "Angsana New", Q_NULLPTR));
        action_8->setText(QApplication::translate("MainWindow", "Cordia New", Q_NULLPTR));
        action_9->setText(QApplication::translate("MainWindow", "\345\271\274\345\234\206", Q_NULLPTR));
        action_10->setText(QApplication::translate("MainWindow", "\346\245\267\344\275\223", Q_NULLPTR));
        action_11->setText(QApplication::translate("MainWindow", "\351\232\266\344\271\246", Q_NULLPTR));
        action_12->setText(QApplication::translate("MainWindow", "\344\273\277\345\256\213", Q_NULLPTR));
        action1->setText(QApplication::translate("MainWindow", "20", Q_NULLPTR));
        action10->setText(QApplication::translate("MainWindow", "21", Q_NULLPTR));
        action20->setText(QApplication::translate("MainWindow", "22", Q_NULLPTR));
        action30->setText(QApplication::translate("MainWindow", "23", Q_NULLPTR));
        action40->setText(QApplication::translate("MainWindow", "24", Q_NULLPTR));
        action25->setText(QApplication::translate("MainWindow", "25", Q_NULLPTR));
        action26->setText(QApplication::translate("MainWindow", "26", Q_NULLPTR));
        action27->setText(QApplication::translate("MainWindow", "27", Q_NULLPTR));
        action28_2->setText(QApplication::translate("MainWindow", "28", Q_NULLPTR));
        action29->setText(QApplication::translate("MainWindow", "29", Q_NULLPTR));
        action30_2->setText(QApplication::translate("MainWindow", "30", Q_NULLPTR));
        action31->setText(QApplication::translate("MainWindow", "31", Q_NULLPTR));
        action32->setText(QApplication::translate("MainWindow", "32", Q_NULLPTR));
        action33->setText(QApplication::translate("MainWindow", "33", Q_NULLPTR));
        action34->setText(QApplication::translate("MainWindow", "34", Q_NULLPTR));
        action35->setText(QApplication::translate("MainWindow", "35", Q_NULLPTR));
        action36->setText(QApplication::translate("MainWindow", "36", Q_NULLPTR));
        actionshx->setText(QApplication::translate("MainWindow", "shx", Q_NULLPTR));
        actionHome_https_lvyingzhao_cn->setText(QApplication::translate("MainWindow", "Home :https://lvyingzhao.cn", Q_NULLPTR));
        actionchangkou->setText(QApplication::translate("MainWindow", "changkou", Q_NULLPTR));
        menuF->setTitle(QApplication::translate("MainWindow", "\346\226\207\344\273\266(&F)", Q_NULLPTR));
        menuE->setTitle(QApplication::translate("MainWindow", "\347\274\226\350\276\221(&E)", Q_NULLPTR));
        menuW->setTitle(QApplication::translate("MainWindow", "\347\252\227\345\217\243(&W)", Q_NULLPTR));
        menuH->setTitle(QApplication::translate("MainWindow", "\345\270\256\345\212\251(&H)", Q_NULLPTR));
        menu_A->setTitle(QApplication::translate("MainWindow", "\345\205\263\344\272\216(&A)", Q_NULLPTR));
        menu->setTitle(QApplication::translate("MainWindow", "\350\203\214\346\231\257\345\272\225\350\211\262(B)", Q_NULLPTR));
        menu_2->setTitle(QApplication::translate("MainWindow", "\345\255\227\344\275\223\350\256\276\347\275\256(Z)", Q_NULLPTR));
        menu_3->setTitle(QApplication::translate("MainWindow", "\345\255\227\345\217\267(M)", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
