"""empty message

Revision ID: 4882b5f38a4f
Revises: 
Create Date: 2020-12-30 23:48:37.227577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4882b5f38a4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stu_info', 'belong')
    op.drop_column('stu_info', 'college')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stu_info', sa.Column('college', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('stu_info', sa.Column('belong', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
