"""empty message

Revision ID: 4895af7f9964
Revises: afa9ae170e59
Create Date: 2021-01-01 23:26:19.829826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4895af7f9964'
down_revision = 'afa9ae170e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stu_info', sa.Column('remarks', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stu_info', 'remarks')
    # ### end Alembic commands ###
