"""empty message

Revision ID: afa9ae170e59
Revises: 82c03acf897b
Create Date: 2021-01-01 23:09:26.491067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa9ae170e59'
down_revision = '82c03acf897b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stu_info', sa.Column('phone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stu_info', 'phone')
    # ### end Alembic commands ###
