"""empty message

Revision ID: c390f267bad2
Revises: 4882b5f38a4f
Create Date: 2020-12-30 23:52:50.918840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c390f267bad2'
down_revision = '4882b5f38a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group')
    )
    op.create_table('stu_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stuNumber', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('age', sa.String(length=256), nullable=True),
    sa.Column('birthday', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('qq', sa.String(length=32), nullable=True),
    sa.Column('mail', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stuNumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stu_info')
    op.drop_table('category')
    # ### end Alembic commands ###
